### ISSUE TITLE
Validação padronização dos arquivos

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-angular#46]
Hoje temos arquivos tanto CamelCase quanto kebab-case.
Validar padronização.

Uma padronização inicial foi adotada considerando:
- Classe é sempre em CamelCase 
- se não tem classe é kebab-case

Se formos manter esse padrão ou se formos considerar algum outro padrão, os arquivos do beagle-angular precisam ser ajustados.

**Comment by rafaeelaudibert** [comment]
Hey, @pedronaveszup @Tiagoperes @carinapetraviciuszup I might be able to work on this :).

I'd suggest always using capitalized PascalCase when we are talking about components or when we are exporting a class from the inside of it. Except that, I'd suggest using camelCase, abolishing kebab-case usage. WDYT?

**Comment by Tiagoperes** [comment]
Hello @rafaeelaudibert. Thanks for your interest. We are currently using the following rule:

- If the file export a class, it's named after the class, in PascalCase.
- Otherwise, the file name must use kebab-case.

We should avoid using uppercase in file names. File names with uppercase letters are not a good practice because different operating systems interpret them differently. For instance, you can have a situation where `MyFile.ts` is interpreted as being the same as `myfile.ts` in Windows, but different in Linux. This can cause a lot of trouble when comiting files to Github or referencing them.

Flutter, for instance, adopted snake_case even for classes. We'll keep using PascalCase for classes because Javascript developers are very used to it. But, for every other file, kebab-case must be used.
